using RPG.VisualNovel;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace RPG.VisualNovel
{
    public class GameController : MonoBehaviour
    {
        public GameScene currentScene;
        public BottomBarController bottomBar;
        public SpriteSwitcher backgroundController;
        public ChooseController chooseController;
        public AudioController audioController;

        private State state = State.IDLE;

        private enum State
        {
            IDLE, ANIMATE, CHOOSE
        }

        void Start()
        {
            if (currentScene is StoryScene)
            {
                StoryScene storyScene = currentScene as StoryScene;
                bottomBar.PlayScene(storyScene);
                backgroundController.SetImage(storyScene.background);
                PlayAudio(storyScene.sentences[0]);
            }
        }

        void Update()
        {
            if (Input.GetKeyDown(KeyCode.Space) || Input.GetMouseButtonDown(0))
            {
                if (state == State.IDLE && bottomBar.IsCompleted())
                {
                    if (bottomBar.IsLastScentence())
                    {
                        PlayScene((currentScene as StoryScene).nextScene);
                    }
                    else
                    {
                        bottomBar.PlayNextSentence();
                        PlayAudio((currentScene as StoryScene)
                                   .sentences[bottomBar.GetSentenceIndex()]);
                    }
                }
            }
        }

        public void PlayScene(GameScene scene)
        {
            StartCoroutine(SwitchScene(scene));
        }

        private IEnumerator SwitchScene(GameScene scene)
        {
            state = State.ANIMATE;
            currentScene = scene;
            bottomBar.Hide();
            yield return new WaitForSeconds(1f);
            if (scene is StoryScene)
            {
                StoryScene storyScene = scene as StoryScene;
                backgroundController.SwitchImage(storyScene.background);
                PlayAudio(storyScene.sentences[0]);
                yield return new WaitForSeconds(1f);
                bottomBar.ClearText();
                bottomBar.Show();
                yield return new WaitForSeconds(1f);
                bottomBar.PlayScene(storyScene);
                state = State.IDLE;
            }
            else if (scene is ChooseScene)
            {
                state = State.CHOOSE;
                chooseController.SetupChoose(scene as ChooseScene);
            }
            else if (scene is null)
            {
                int currentSceneIndex = SceneManager.GetActiveScene().buildIndex;
                SceneManager.LoadScene(currentSceneIndex + 1);
            }
        }

        private void PlayAudio(StoryScene.Sentence sentence)
        {
            audioController.PlayAudio(sentence.music, sentence.sound);
        }
    }
}